apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: model-monitoring
resources:
  - podmonitor-kserve-predictors.yaml
  - servicemonitor-dcgm-exporter.yaml
  - prometheus-rules.yaml