apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: gitops
  namespace: devcluster-monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  resyncPeriod: 5m
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  title: GitOps
