apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: model-monitoring

resources:
  - grafana-rbac.yaml
  - grafana-sa.yaml
  - grafana.yaml
  - grafana-datasource.yaml
  - grafana-folder.yaml
  - grafana-dashboard-local-models.yaml
  - grafana-dashboard-ai-providers.yaml
