apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: model-monitoring

resources:
  - grafana-deployment.yaml
  - grafana-service.yaml
  - grafana-route.yaml

configMapGenerator:
  - name: grafana-datasources
    files:
      - prometheus-datasource.yaml=datasource-prometheus.yaml
  - name: grafana-dashboards
    files:
      - local-models-dashboard.json=dashboards/local-models-dashboard.json
      - external-usage-dashboard.json=dashboards/ai-providers-dashboard.json

generatorOptions:
  disableNameSuffixHash: true