apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - grafana-rbac.yaml
  - grafana-prometheus-sa.yaml
  - grafana.yaml
  - grafana-datasource.yaml
  - grafana-folder.yaml
  - grafana-dashboard-rhoai-models-registry.yaml
  # - grafana-dashboard-ai-providers.yaml
  - grafana-dashboard-rolling-demo.yaml
  - rolling-demo-prometheus-rules.yaml
