apiVersion: apps/v1
kind: Deployment
metadata:
  name: robotheus-exporter
  namespace: devcluster-monitoring
  labels:
    app: robotheus-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: robotheus-exporter
  template:
    metadata:
      labels:
        app: robotheus-exporter
    spec:
      containers:
        - name: exporter
          image: ghcr.io/thepetk/robotheus:v0.1.7
          args:
            - --log.level=debug
          ports:
            - name: metrics
              containerPort: 9185
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: robotheus-secrets
                  key: OPENAI_API_KEY
            - name: OPENAI_ORG_ID
              valueFrom:
                secretKeyRef:
                  name: robotheus-secrets
                  key: OPENAI_ORG_ID
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
