apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: devcluster-monitoring
resources:
  - ai-providers-deployment.yaml
  - ai-providers-service.yaml
  - ai-providers-servicemonitor.yaml
  - prometheus-rules.yaml