apiVersion: apps/v1
kind: Deployment
metadata:
  name: openai-exporter
  labels:
    app: openai-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openai-exporter
  template:
    metadata:
      labels:
        app: openai-exporter
    spec:
      containers:
        - name: openai-exporter
          image: foxdalas/openai-exporter:v0.0.14
          args:
            - -web.listen-address=:9185
            - -web.telemetry-path=/metrics
            - -scrape.interval=5m
          env:
            - name: OPENAI_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-exporter-secret
                  key: OPENAI_SECRET_KEY
            - name: OPENAI_ORG_ID
              valueFrom:
                secretKeyRef:
                  name: openai-exporter-secret
                  key: OPENAI_ORG_ID
          ports:
            - name: metrics
              containerPort: 9185
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 512Mi
