apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: model-monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/thepetk/model-observability-gitops.git
    targetRevision: HEAD
    path: apps/monitoring/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: model-monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true