apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: model-monitoring

configurations:
  - kustomize-prometheus-config.yaml

resources:
  - namespace.yaml
  - grafana
  - rhoai-models-registry
  # - ai-providers